ydl:
  mysql:
    database: ydl_sms
  swagger:
    enabled: true
    docket:
      sms:
        title: 短信发送服务
        base-package: com.ydl.sms.controller
  sms: 
    messageErrorNum: 3
    configLevelFailNum: 10
    configBuildScale: 0.75
    
authentication:
  user:
    header-name: token
    expire: 43200
    pri-key: client/pri.key
    pub-key: client/pub.key
server:
  port: 8772

spring:
  cache:
    type: REDIS
  redis:
    database: 1
    host: 47.120.7.87 # Redis服务器地址
    port: 16380 # Redis服务器连接端口
    password: 123456
    timeout: 10000ms
    lettuce:
      pool:
        max-active: 200
        max-idle: 20
        min-idle: 3
        max-wait: -1ms
    sentinel:
      master: mymaster
      nodes:
        - 47.120.7.87:26380
        - 47.120.7.87:26381
        - 47.120.7.87:26382
    queue:
      pop:
        timeout: 8000